CHANGELOG.md
docs/source/javascript/_event-bus.md
docs/source/table_of_contents.yml
lib/js/calcite-web.js
lib/sass/calcite-web/patterns/_accordion.scss

Final Accordion

---

.travis.yml
README.md

Now that calcite-web is open source, we can add cool stuff!
For now tests only run the linter, but I would love to set it up so that it tested all of our patterns as well.

travis, badges

---

Gruntfile.js

apparently trailing spaces in the mime type are no bueno...

fix s3 upload

---

CHANGELOG.md
lib/sass/calcite-web/components/_dropdown.scss
lib/sass/calcite-web/patterns/_filter-dropdown.scss

small changes to max height of filter-dropdowns, dropdowns

---

CHANGELOG.md
README.md
docs/source/components/sample-code/_checkboxes.html
docs/source/components/sample-code/_radio-buttons.html
docs/source/page-layouts/type-comparison.html
lib/sass/calcite-web/components/_form.scss
package.json

document type face internationalization properly

---

CHANGELOG.md
lib/sass/calcite-web/components/_dropdown.scss

#591 - fix usernav and dropdown-btn in IE10

---

docs/source/examples/core.html
docs/source/examples/core/_cards.html
docs/source/examples/e-commerce.html
docs/source/examples/extentions.html
docs/source/examples/index.html
docs/source/examples/quickstart.html
docs/source/layouts/_examples.html

well, the rough structure for what the top index will be

Basic Copy/Paste Examples

---

CHANGELOG.md
lib/sass/calcite-web/type/_mixins.scss

where others have fallen, I will succeed.
@nikolaswise

#614 - numbered list off in IE11

---

CHANGELOG.md
lib/js/helpers/aria.js
lib/js/patterns/modal.js

Made aria helper more robust to arrays with null values.
Updated modal to prevent passing arrays with null values to helpers.

Fix for issue #656

---

CHANGELOG.md
docs/source/documentation/grid/_block-groups.md
docs/source/documentation/grid/_responsive-block-groups.md
docs/source/documentation/javascript/_overview.md
docs/source/search.html
lib/sass/calcite-web/components/_card.scss
lib/sass/calcite-web/components/_label.scss
lib/sass/calcite-web/components/_table.scss
lib/sass/calcite-web/grid/_block-groups.scss

@nikolaswise lots of smaller fixes and documentation updates

update documentation for javascript, small fixes

---

CHANGELOG.md
docs/source/assets/css/all.scss
docs/source/examples/navigation/_global-nav.html
docs/source/guides/best-practices/forms.md
docs/source/guides/best-practices/index.md
docs/source/guides/best-practices/typography.md
docs/source/layouts/_designguide.html
docs/source/layouts/_examples.html
docs/source/layouts/_guide.html
lib/js/calcite-web.js
lib/js/helpers/clipboard.js
lib/sass/calcite-web/patterns/_top-nav.scss
package.json

Stub some best practices, get copy to clipboard in there, start working the top nav a little bit with input from developers.

Copy to Clipboard

---

lib/sass/calcite-web/grid/_columns.scss

all column classes now receive base styles individually, instead of with a wildcard selector

make column selector less wild-card-y

---

CHANGELOG.md
lib/js/patterns/dropdown.js

@paulcpederson could probably be cleaned

Dropdown Movement

---

CHANGELOG.md
lib/js/calcite-web.js
lib/js/helpers/event.js
lib/js/patterns/accordion.js

Accordions stopped working after first init. 
@nikolaswise

fix rebinding of accordion events, and subsequent init events

---

README.md

Noticed this while reading the docs.

Grammar fix.

---

CHANGELOG.md
lib/sass/calcite-web/patterns/_modal.scss
lib/sass/calcite-web/patterns/_search.scss
lib/sass/calcite-web/patterns/_tabs.scss
lib/sass/calcite-web/patterns/_top-nav.scss

Almost all of the open issues are taken care of now with this pull request.

Small fixes in preparation for next release

---

CHANGELOG.md
docs/source/assets/js/search.js
docs/source/documentation/components/sample-code/_card.html
docs/source/documentation/get-started/_ruby-gem.md
docs/source/documentation/patterns/sample-code/_search.html
docs/source/layouts/_layout.html
docs/source/search.html
lib/sass/calcite-web/components/_form.scss
lib/sass/calcite-web/patterns/_footer.scss
lib/sass/calcite-web/patterns/_modal.scss
lib/sass/calcite-web/patterns/_search.scss
lib/sass/calcite-web/patterns/_top-nav.scss

fixes a couple open issues as well as some bugs that weren't documented esp. related to mobile safari.

Small fixes

---

dist/sass/calcite-web/components/_dropdown.scss
lib/sass/calcite-web/components/_loader.scss

Fix #764: Align dropdown-btn in IE

---

docs/source/guides/code/html.md

Just saw this in @alaframboise DevSummit presentation.

HTML Styleguide: Typo fix

---

docs/source/assets/css/slides.scss
docs/source/assets/js/slides.js
docs/source/layouts/_layout.html
docs/source/layouts/_presentation.html
docs/source/presentations/calcite-web-deep-dive.html
docs/source/presentations/calcite-web-primer.html

Adding the presentations from the workshop to the documentation site. 
1. Simple JS that runs slides
2. Tiny set of CSS styles for showing/hiding slides
3. Slide content for two presentations
4. Links to both presentations from the footer

add workshop slides to documentation

---

presentations/calcite-web-deep-dive/index.html
presentations/calcite-web-primer/index.html

just adding another link to more aria role documentation thats a little less terse. very cool presentations!

typo fix and extra aria link

---

docs/source/documentation/patterns/sample-code/_tabs.html
lib/js/patterns/tabs.js

mouse click would not fire if child element was clicked

Added a fix for when a tab heading has a child element - 

---

docs/source/documentation/components/_animation.md

the snoop has been reading your doc again!
🕵️  not 🐶  (unfortunately)

the tiniest of typos

---

docs/source/layouts/_doc.html
docs/source/layouts/_examples.html
docs/source/quick-reference/index.html

Fix typos, clean up styles

---

lib/sass/calcite-web/components/_form.scss

Small update to some values for radio and checkbox spacing cross-browsers

Update spacing values

---

docs/source/guides/quickstart/demo.html
docs/source/guides/quickstart/index.html

1. Closed up gaps in <h*> levels for WAVE test
2. Applied above change and change in earlier PR for Chrome Lighthouse test to quickstart's demo page

Accessibility changes

---

docs/source/guides/quickstart/demo.html
docs/source/guides/quickstart/index.html

The first two headings are "Header 2"; the next two are "Header 3" and "Header 4". Assuming that a series was intended.

Fixed minor typo

---

docs/source/documentation/components/_alerts.md
docs/source/guides/migration-guide.md

s/be default/by default

---

CHANGELOG.md
docs/source/documentation/grid/_configuration.md
lib/sass/calcite-web/base/_config.scss

remove unused grid fallbacks

---

lib/sass/calcite-web/patterns/_modal.scss
lib/sass/calcite-web/patterns/_search.scss

Vertical alignment was never this easy…

Flexbox Modals

---

CHANGELOG.md
lib/sass/calcite-web/patterns/_filter-dropdown.scss

Fixes the RTL issues and cleans up spacing a bit

Fix filter dropdown in RTL, clean up styles

---

docs/source/documentation/patterns/sample-code/_filter-dropdown.html
lib/js/patterns/filter-dropdown.js

This looks like a typo, but wanted to check

Changed spelling of "js-flilter-dropdown-no-filters"

---

CHANGELOG.md
lib/sass/calcite-web/patterns/_accordion.scss

Fix for https://github.com/Esri/calcite-web/issues/950

Add RTL support for accordion caret

---

docs/source/guides/mobile.md

First stab at the content for a guide on building responsive experiences with Calcite Web

write mobile guide

---

CHANGELOG.md
lib/sass/calcite-web/utils/_positioning.scss

Adds unset to positioning mixins

---

lib/sass/calcite-web/components/_radio-group.scss

Keeps fix for radio group and uses new mixin

Add mixin with initial border-left fix

---

CHANGELOG.md
docs/source/documentation/components/_form-overview.md

Fix for https://github.com/Esri/calcite-web/issues/1053

Fix for terminology in form documentation

---

lib/sass/calcite-web/components/_dropdown.scss

Tiny change to the dropdown update that was just merged in.

Darken header type color in dropdown

---

CHANGELOG.md
lib/sass/calcite-web/patterns/_accordion.scss

Some changes to accordions...
Consolidates spacing of content area to one property
Uses flexbox to position title / caret to allow for wrapping lines
Updates changelog
Note: 
The border highlight hover flashing is still bothersome, but can maybe be addressed later.

Updates to accordion styling, update changelog

---

docs/source/documentation/patterns/sample-code/_pagination.html
lib/sass/calcite-web.scss
lib/sass/calcite-web/patterns/pagination.scss

updated styles for pagination #1012

Pagination

---

lib/sass/calcite-web/patterns/pagination.scss

Pagination rtl
