Esri/calcite-web

CHANGELOG.md
lib/sass/calcite-web/components/_form.scss

I thought the `select[multiple]` element looked a bit off. Removed the padding from the select and added it to the option. It looks like this now:
Which I think makes it look a little more like our existing patterns like side nav, dropdown, drawers, etc.
/cc @nikolaswise

small update to select[multiple]

---

CHANGELOG.md
lib/sass/calcite-web/components/_button.scss

solid red buttons call far too much attention to themselves. Since red is usually used as a destructive action, it's important for it to not be the top of the visual hierarchy.

make red buttons outlined

---

CHANGELOG.md
lib/sass/calcite-web/components/_form.scss

fix alignment of checkboxes and radiobuttons in IE10

---

CHANGELOG.md
docs/source/table_of_contents.yml
lib/sass/calcite-web/patterns/_tabs.scss

- added modifier to table of contents
- adding translucent pattern `.tabs-translucent` for tabs
- dark variation of translucent with modifier `.tabs-dark`
- fixed issue with default transition being spelled wrong `backround` to `background`

translucent tab pattern - light and dark

---

Gruntfile.js
bin/stat.js
package.json

@nikolaswise this adds a grunt task that will build sass and then spit out some stats on the main bundle (`dist/css/calcite-web.css`).
Just run `grunt stat` and it will build everything and then output some info:
```
size:      354kB
gzipped:   33kB
rules:     3182
selectors: 4452
```
This is a really dumb version of something that could be really cool, but it will at least give us an easy way to trouble shoot the the IE9 limit problem.

add grunt stat method to get basic stats about css bundle

---

lib/sass/calcite-web/grid/_block-groups.scss

There is no CHANGELOG because developers use it exactly the same. It should just swap out flawlessly with the old implementation.
Because flex-box is IE10+, I make the `block` class float in IE9 and add a `clearfix` to the `block-group` class. So visually it still works. 
Another nice thing about this implementation is that the gutters are done with margin instead of padding, meaning you don't have to wrap each block in an additional div.
I have tested this on the example page on IE9, IE10, IE11, Safari, Firefox, and Chrome. Seems to work great. It will also enable us to have equal height blocks by default which is pretty cool.
/cc @nikolaswise

implement block-groups with flex-box

---

README.md

I had problems trying to install without the double quotes, i got an error -> zsh: no matches found: Esri/calcite-web#v1.0.0-beta.30

Updating how to install via npm

---

package.json

adds `npm run dist` to build the dist assets, and fixes errors from the rollup babel integration
/cc @nikolaswise

add babel configuration and dist task

---

CHANGELOG.md
lib/sass/calcite-web/components/_card.scss

@nikolaswise I was just using cards in a smaller UI and the padding felt huge. I htink 1 rem is a good compromise.

reduce padding for card content

---

lib/sass/calcite-web/grid/_columns.scss
lib/sass/calcite-web/grid/_pre-post.scss

The pre and post sizing is sometimes slightly too large by fractions of a pixel. In firefox, in some cases this is rounded *up* and the columns break to the next row. 
#701
@patrickarlt

fix rounding error in pre+post column sizing

---

CHANGELOG.md
docs/source/documentation/components/_panels.md
docs/source/documentation/components/sample-code/_images.html
docs/source/documentation/components/sample-code/_panels.html
lib/img/forward-slash-white.svg
lib/img/forward-slash.svg
lib/sass/calcite-web/components/_breadcrumbs.scss
lib/sass/calcite-web/components/_form.scss
lib/sass/calcite-web/patterns/_top-nav.scss
lib/sass/calcite-web/type/_scale.scss
lib/sass/calcite-web/type/_styles.scss
package.json

- much better implementation for breadcrumbs
- fix 404s in doc
- reduce built CSS size with small optimization to `font-size` mixin
- top-nav-title has no blue underline now on hover/focus
- remove opinionated styles from `figcaption`
- fix `input type="search"` in Safari (broken since `v1.0.0-rc.0`)
- small improvement to text rendering in Safari

Style Updates

---

CHANGELOG.md
CONTRIBUTING.md
docs/source/assets/css/all.scss
docs/source/table_of_contents.yml
lib/js/patterns/accordion.js
lib/js/patterns/search.js
lib/sass/calcite-web/components/_alert.scss
lib/sass/calcite-web/components/_button.scss
lib/sass/calcite-web/components/_dropdown.scss
lib/sass/calcite-web/components/_loader.scss
lib/sass/calcite-web/patterns/_tabs.scss

Improve the `CONTRIBUTING` document with less verbose explanation of adding a component. Try to only include essential explanations and make it more beginner-friendly.
Also addresses the following open issues:
#776 - add right to left styles for tab pattern
#774 - enter keypress on element inside accordion should not close accordion
#771 - fix alignment of short `loader-text` messages
#770 - add right to left support for `dropdown-right`
#768 - don't style `button` tags directly :warning: BREAKING :warning:
#767 - add `alert-full` modifier
#763 - fix strange behavior with search js

Update CONTRIBUTING, fix several bugs

---

CHANGELOG.md
dist/css/calcite-web-dark.css
dist/css/calcite-web-no-fonts.css
dist/css/calcite-web.css
dist/sass/calcite-web/grid/_leader-trailer.scss
docs/source/documentation/grid/_gutter.md
docs/source/table_of_contents.yml
lib/sass/calcite-web/grid/_leader-trailer.scss

Mixins and classes for adding top or bottom margin or padding that is 25% of `$baseline`.
- `leader-quarter()`
- `trailer-quarter()`
- `padding-leader-quarter()`
- `padding-trailer-quarter()`
- `.leader-quarter`
- `.trailer-quarter`
- `.padding-leader-quarter`
- `.padding-leader-quarter`
- `.large-leader-quarter`
- `.large-trailer-quarter`
- `.large-padding-leader-quarter`
- `.large-padding-leader-quarter`
- `.tablet-leader-quarter`
- `.tablet-trailer-quarter`
- `.tablet-padding-leader-quarter`
- `.tablet-padding-leader-quarter`
- `.phone-leader-quarter`
- `.phone-trailer-quarter`
- `.phone-padding-leader-quarter`
- `.phone-padding-leader-quarter`
Updated Gutter docs. No more classes named `gutter-`.

Leader/Trailer: Add quarter variants

---

README.md

custom markdown tags are no longer hidden.
in `v2` of esri.github.io we'll be showcasing this project and relying on some new canned [`topics`](https://github.com/blog/2309-introducing-topics)
at a minimum, can you add `web-development` as one please?

remove esri tags from readme

---

docs/source/examples/core/_features.html

... down at the bottom of [/examples/core/](http://esri.github.io/calcite-web/examples/core/)

fix for broken thumbnails

---

dist/sass/calcite-web/type/_config.scss

- Removes 5 fallbacks from `$avenir-family`.
- Removes 2 fallbacks from `$code-family`.
- `Avenir Next W01` and `Avenir Next W00` are no longer available.
- `Helvetica` and `Arial` are already the default sans-serif fonts on
their respective operating systems.
- `Courier New` and `Courier` are already the default sans-serif fonts
on their respective operating systems.
See:
https://www.granneman.com/webdev/coding/css/fonts-and-formatting/web-bro
wser-font-defaults/
- Should `Avenir` be used as a fallback? Are there situations where it should be used and Avenir Next will not be available?

Simplify font stack

---

docs/source/presentations/calcite-web-deep-dive.html

`<a>` tags are infinitely more clickable when they include real text.
(and now i understand that your `gh-pages` source is actually maintained in `master`)

second attempt at supplementing aria roles external doc

---

package.json

Update from 2.0 -> 3.0, resolves issue as found on GitHub:
https://github.com/darkguy2008/parallelshell/issues/57
Adds support for Node  >= 8

Bump Parallelshell Version

---

CHANGELOG.md
lib/sass/calcite-web/components/_button.scss

Ensure border and background colors match on hover. For clear-white, show same color border on hover to maintain correct width.
Update to requested style, making sure other button colors and styles match the paradigm: https://github.com/Esri/calcite-web/issues/840

Update button border hover styles

---

CONTRIBUTING.md
docs/source/assets/css/quick-reference.scss
docs/source/layouts/_doc.html
docs/source/layouts/_examples.html
docs/source/layouts/_guide.html
docs/source/layouts/_layout.html
docs/source/layouts/_quick-reference.html
docs/source/quick-reference/changelog/index.html
docs/source/quick-reference/class-sheet/index.html
docs/source/quick-reference/index.html
docs/source/search.html
docs/source/table_of_contents.yml

This adds a basic implementation of a component status table. We can work with the terminology and add features later but felt it was important to get a basic version up. Also adds a changelog and a few style clean up items here and there.
- Add Component Status to Quick Reference section
- This is generated from status attributes defined in table_of_contents.yml
- Added two new table_of_contents attributes
- Status: (this is used to populate the Component Status sheet)
- ‘complete’
- ‘inprogress’
- ‘proposed’
- ‘unplanned’
- false
- —
- These will populate the component index sheet with status marks, and link to component docs. You can set ‘status: false’ to hide a component from the index sheet (also useful for hiding Overview, etc).
- Hidden: (this is used to hide groups and components …

Quick Reference Improvements

---

CHANGELOG.md

in case you change your mind about what the version number ends up being.
also, right now it looks like you've already published [`v1.0.0`](http://esri.github.io/calcite-web/quick-reference/changelog/)

use 'unreleased' in the changelog instead of the next planned version number

---

lib/sass/calcite-web/components/_form.scss

Fixes for https://github.com/Esri/calcite-web/issues/861 ...
Makes radio inputs display as such on iOS
Browser-specific adjustments to make alignment more consistent
Fixed iOS display of input file upload button
Alignment aside, all browsers display these radios and checkboxes differently, could be a candidate for another pass down the road to make the styles themselves more consistent.

Radio button and checkbox iOS and alignment fixes

---

docs/source/assets/css/_doc.scss
docs/source/assets/css/_theme.scss
docs/source/assets/css/dark.scss
docs/source/assets/css/extensions.scss
docs/source/assets/js/theme.js
docs/source/documentation/components/sample-code/_form-overview.html
docs/source/documentation/components/sample-code/_switches.html
docs/source/layouts/_layout.html
docs/source/table_of_contents.yml
lib/sass/calcite-web/components/_sliders.scss
lib/sass/calcite-web/components/_switches.scss

Please give this a look over... Basically just setting a string that matches theme title in localstorage and retrieving it on load / changing it on click. The fade animations are stored in an always present css file to alleviate flash in as much as possible.
Of course some weird browser issues exist... Firefox is the offender here requiring us to set disabled via JS on load as it doesn't interpret the "disabled" in the markup itself. It seems to handle switching themes the worst since the disabled value is set after load. Tested and working down to IE10.
Occasionally, there remains a short flash as the stylesheet is swapped, so all ears if there's a better solution. The content itself is actually styled but the switch from #fff to #000 is abrupt.
Open to moving it somewhere less prominent …

Dark Theme Docs Toggle

---

lib/sass/calcite-web/type/_styles.scss

Fix for https://github.com/Esri/calcite-web/issues/888

Wrap long code strings by default

---

CHANGELOG.md
lib/sass/calcite-web/base/_config.scss

Setting the `$vw-ratio` slightly higher solved this problem. Here is some background information to this rather strange variable and why this fixes the problem:
It seems like if you have a grid that's based on vw units, you could use `100vw` as the your width, and subdivide that by however many columns and be done with it, right? _Wrong_. On certain browsers, the width of the scroll bar is _part_ of the `100vw`, so if you have column widths that add up to 100, and the user has scroll bars turned on, the second column breaks to the next line. 
Because of this, we added the `$vw-ratio` variable that sets the max container size at slightly less than `100vw`. 
Previously this variable was set to `.95`, which mean that every column was `95 / 24`, or `3.9583333333`. By moving to `.96` this …

#742 - fix rounding error by making column max more even

---

docs/acetate.config.js

Fix for https://github.com/Esri/calcite-web/issues/913 ...
reference: 
http://acetate.io/documentation/configuring-markdown-it/
https://github.com/markdown-it/markdown-it#syntax-highlighting

Fix for tabindex on code blocks in docs

---

docs/source/index.html

Noticed a closing `</tbody>` was missing.

Missing </tbody> tag.

---

CHANGELOG.md
docs/source/assets/css/_doc.scss
docs/source/assets/css/all.scss
docs/source/assets/css/dark.scss
docs/source/assets/css/imports.scss
docs/source/examples/grid/index.html
docs/source/layouts/_layout.html
lib/sass/calcite-web/base/_config.scss
lib/sass/calcite-web/components/_button.scss
lib/sass/calcite-web/grid/_pre-post.scss
lib/sass/calcite-web/imports.scss
lib/sass/calcite-web/type/_scale.scss
lib/sass/calcite-web/type/_styles.scss

- Change type size from 17px to 16px (#889)
- All line heights are not unit-less, so they inherit/cascade better (#847)
- base line-height is now 1.5 instead of 1.55, this keeps type spacing at whole pixels most of the time (#826)
- Fixed a couple bugs with pre/post as well
- Explicitly set all vars to `false` in imports to reduce the chance of multiple inclusions of built CSS when importing mixins

v1.0.0 fixes

---

docs/source/examples/grid/index.html

* <kbd>.column-24</kbd> > <kbd>column-24</kbd>
* <kbd>.column-8.center-column</kbd> > <kbd>column-8 center-column</kbd>
for consistency with http://esri.github.io/calcite-web/documentation/grid/#columns

remove the '.'s from /examples/grid/

---

CHANGELOG.md
docs/source/examples/grid/index.html
lib/sass/calcite-web/base/_config.scss
lib/sass/calcite-web/grid/_pre-post.scss

This means that each columns width once we hit the upper limit is now an even pixel value. This will help with rounding errors from fractional lengths.
#826

make grid container default size 1440px

---

CHANGELOG.md
docs/acetate.config.js
docs/source/documentation/components/_tables.md
docs/source/documentation/components/sample-code/_tables.html
docs/source/documentation/sass/_ui-variables.md
docs/source/index.html
docs/source/presentations/calcite-web-deep-dive.html
lib/sass/calcite-web/base/_config.scss
lib/sass/calcite-web/components/_table.scss

I've cherry-picked @oknoway 's commit, and then changed a few things:
- added `CHANGELOG` entry
- changed the text of the documentation to reflect the new markup/class
- updated acetate to use the `table` class in markdown tables
- changed the variable name from `$prefix-tables` to `$namespace-tables`
- removed the change to `dist` folder (we'll update that on release)
- documented `$easing-function`

#852 - table elements must now use .table class to receive styling

---

docs/source/documentation/components/_buttons.md

When I tried to use btn-link, I added it as a modifier because of the wording "provides an additional class". It wasn't until I opened up the source that I saw that "btn-link" is an alternate to "btn".  Perhaps changing "additional" and adding an example will help.

Propose to slightly reword Button Links doc section and add an example

---

CHANGELOG.md
lib/sass/calcite-web/type/_import.scss

Turns out, the characters from the font we were using for Thai changed the baseline for all the characters in Edge and only Edge. I've disabled the Thai subset and will work with Monotype to get a font that renders properly in Edge.

#929 - fix text baseline in Edge

---

CHANGELOG.md
docs/source/documentation/grid/_configuration.md
lib/sass/calcite-web/base/_config.scss

#836 turns out these variables were never used anywhere, so I removed them.

remove unused grid fallbacks

---

CONTRIBUTING.md
docs/source/assets/css/_doc.scss
docs/source/layouts/_doc.html
docs/source/table_of_contents.yml

Here's an attempt to find some middle ground... This is really only a docs issue since we have to constrain what would be full-width items into their example containers. Unfortunately that means we can't ALSO have vertical overflow (https://www.brunildo.org/test/Overflowxy2.html).
I added a modifier class we can apply in the table of contents to allow overflow-y on a per-component basis. It works for the dropdowns (https://github.com/Esri/calcite-web/issues/944) but it has the potential to cause overflow-x problems if added to other components, so it's not totally ideal. 
I don't think we want to get in the habit of it, but it's possible to pass other classes in the table of contents for additional styling as well.

Add doc example styling option

---

lib/js/calcite-web.js

greetings!
_**not** a dealbreaker_, but i noticed that the version number in the copyright header for all [`v1.0.1`](https://github.com/Esri/calcite-web/blob/master/dist/js/calcite-web.min.js) files are out of sync with the actual release.
> /*!
> * Calcite Web - Calcite Design Components in CSS, JS and HTML
> * @version v1.0.0
> * @license Apache-2.0
digging in a little, everything looks okay with your [rollup.config](https://github.com/Esri/calcite-web/blob/6c5609a9729e85c59e3e673eeec68e072425d967/lib/js/rollup.config.js#L7) and since `v1.0.0` doesn't have the same problem, maybe it was just the order of operations specifically when you [tagged](https://github.com/Esri/calcite-web/blob/master/CONTRIBUTING.md#bumping-the-version) the first patch?
either way, congrats on exiting the beta!

fix broken link in code comment

---

lib/js/helpers/event.js
lib/js/patterns/modal.js

This fixes the "duplicate modal listener" issue detailed in #954.
Similar to the pattern in [dropdowns](https://github.com/Esri/calcite-web/blob/master/lib/js/patterns/dropdown.js#L49), check if the `click` event is already there before adding it to the modal toggles.
Note that `toggleClick` is moved outside the function `modal`. Otherwise, when calling `modal()` multiple times, duplicate events are getting bound. This is because the [toggle click method](https://github.com/skitterm/calcite-web/blob/058ec14ac0ddf3d71d24c16d97b73bf81bedd38f/lib/js/patterns/modal.js#L78) is a different instance of the function each time `modal()` is called. Sticking it outside of the `modal` function ensures that it's the same instance of the function used by all modals (so the `e.fn === toggleClick` …

Modals without duplicate event listeners

---

docs/source/data/repo.js
package.json

Instead of using the current approach of fetching the repo data over GitHub's REST API, this simply parses the local git repo and finds the last commit and uses that date. This will solve the "last updated at NaN, NaN" problem.

use last commit from local git repository for updated date

---

CHANGELOG.md
lib/sass/calcite-web/components/_switches.scss

`input[type="checkbox"], input[type="radio]"` in `_forms.scss` overrides the `.toggle-switch-input` styles. In some instances, this leads to `.toggle-switch-input` becoming visible.
Adding an empty attribute selector gives `.toggle-switch-input` enough weight to override.

Toggle Switch: Add attribute selector to input

---

CHANGELOG.md
lib/sass/calcite-web/components/_form.scss

Fix for https://github.com/Esri/calcite-web/issues/990 - swaps alignment of icon and error message arrow.

Flips form validation icons and message for RTL

---

CHANGELOG.md
lib/sass/calcite-web/components/_alert.scss
lib/sass/calcite-web/components/_badges.scss
lib/sass/calcite-web/components/_dropdown.scss
lib/sass/calcite-web/components/_form.scss
lib/sass/calcite-web/components/_radio-group.scss
lib/sass/calcite-web/components/_switches.scss
lib/sass/calcite-web/components/_table.scss
lib/sass/calcite-web/components/_tooltip.scss
lib/sass/calcite-web/patterns/_filter-dropdown.scss
lib/sass/calcite-web/patterns/_modal.scss
lib/sass/calcite-web/patterns/_side-nav.scss
lib/sass/calcite-web/type/_mixins.scss
lib/sass/calcite-web/type/_styles.scss
lib/sass/calcite-web/utils/_border.scss
lib/sass/calcite-web/utils/_positioning.scss
lib/sass/calcite-web/utils/_utils.scss
package-lock.json
package.json

As we are supporting RTL with our app that is using CW, we found a series of missing mixins:
- position-right -> position:right (right is already used for float: right)
- position-left -> position:left  (left is already used for float: left)
- border-right
- border-left
- border-color-right
- border-color-left

Implement additional mixins for supporting RTL

---

docs/source/assets/js/all.js

Sets menuData explicitly, this was breaking page JS on 2.0 branch in IE 11... 🙄

2.0 - Fix for IE11 Global Nav issue

---

CHANGELOG.md
docs/source/documentation/components/sample-code/_dropdowns.html
lib/sass/calcite-web/components/_dropdown.scss
lib/sass/calcite-web/utils/_active-link-dot.scss
lib/sass/calcite-web/utils/_utils.scss

PR for https://github.com/Esri/calcite-web/issues/1021.
This builds on Julio's work to update the style of dropdown menus - there are no structural changes. Tested in Chrome, FF, Safari, Edge. Waiting for https://github.com/Esri/calcite-web/pull/1070 to test in IE 11.
Changes:
- These should now match Online / discussed updates
- Hit areas for dropdown links are now full width, and have distinct hover / focus states
- Introduces an `active-link-dot` mixin to use in future designs
- Uses shadow level / strength from Alerts (https://github.com/Esri/calcite-web/pull/1068)
- Uses invocation animation from Online
Questions / Need feedback on:
- Is using `content: "\2022"` for the pseudo-element active dot sustainable? It makes aligning the active dot with the line-height easy but unsure if …

#1021 - Dropdowns

---

docs/source/assets/css/_doc.scss
docs/source/documentation/get-started/_get-started.md
docs/source/documentation/get-started/_static-files.md
docs/source/documentation/javascript/_importing.md
docs/source/documentation/patterns/_interactive-overview.md
docs/source/guides/quickstart/demo.html
docs/source/guides/quickstart/index.html
docs/source/index.html
docs/source/layouts/_doc.html
docs/source/layouts/_examples.html
docs/source/layouts/_guide.html
docs/source/layouts/_layout.html
docs/source/layouts/_quick-reference.html
docs/source/table_of_contents.yml

🫡
Adds deprecation content to the Calcite Web documentation site:
- Persistent alert across all pages.
- Removal of any "patterns.esri.com" CDN references
- Addition of "self host" verbiage
- Removal of placeholder items in status page
We will add more messaging to this repository in the future, but we want to immediately remove the outdated CDN links, per security request from IST.
@paulcpederson - I think you are the only one able to review this 😭 
cc @jcfranco @driskull @juliepowell @geospatialem @brittneytewks

Update site with deprecation content
